Map<String, dynamic> remoConfDefaults = {
  'hideInnerSalesScreen': false,
  'show_Info_popup': true,
  'Offer_Type': 'OTON',
  'showOTOOnAppStart': false,
  'showAreYouSurePopup': true,
  'RewardOFF': false,
  'NoThanksBtnOFF': false,
  'AreYouSurePopupActiveID': 0,
  'AreYouSurePopupConfigs': [
    {
      "id": 0,
      "are-you-sure-title-text": {
        "en": "Are you sure you want to lose this One Time Offer?",
        "de": "",
        "pt": "",
        "ru": "",
        "es": "",
        "it": "",
        "tr": "",
        "fr": "",
        "zh": "",
        "jp": "",
        "kr": "",
        "ar": ""
      },
      "back-to-oto-enabled": true,
      "back-to-oto-screen-text": {
        "en": "Back to offer details",
        "de": "",
        "pt": "",
        "ru": "",
        "es": "",
        "it": "",
        "tr": "",
        "fr": "",
        "zh": "",
        "jp": "",
        "kr": "",
        "ar": ""
      },
      "purchase-offer-enabled": true,
      "purchase-offer-text": {
        "en": "Unlock full app now!",
        "de": "",
        "pt": "",
        "ru": "",
        "es": "",
        "it": "",
        "tr": "",
        "fr": "",
        "zh": "",
        "jp": "",
        "kr": "",
        "ar": ""
      },
      "skip-to-app-enabled": true,
      "skip-to-app-text": {
        "en": "Lose this offer",
        "de": "",
        "pt": "",
        "ru": "",
        "es": "",
        "it": "",
        "tr": "",
        "fr": "",
        "zh": "",
        "jp": "",
        "kr": "",
        "ar": ""
      }
    }
  ],
  'OTO_Types_Configs': [
    {
      "id": "OTON",
      "all-oto-iap-remove-ads": true,
      "ImagesConfig": {
        "header-title-image": "",
        "copy-image": "",
        "offer-disappears-image": "",
        "no-thanks-image": ""
      },
      "FullPriceConfig": {
        "QonversionID": "",
        "Pre-Price-Text": {
          "en": "Instead of the regular price of ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Price": "14.99",
        "Post-Price-Text": {
          "en": "per month",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Pre-Discount-text": {
          "en": "grab a coupon and get more than ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "DiscountPercent": "90"
      },
      "LeftOfferConfig": {
        "QonversionID": "QON ID HERE",
        "Price": "5.99",
        "Post-Price-Text": {
          "en": " / month after trial",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Box-Text": {
          "en": "Monthly subscription            after 3 days FREE",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Button-Title": {
          "en": "CONTINUE",
          "de": "Weiter",
          "pt": "Continuar",
          "ru": "Продолжить",
          "es": "Continuar",
          "it": "Continua",
          "tr": "Devam Et",
          "fr": "Continuez",
          "zh": "繼續",
          "jp": "続行する",
          "kr": "이어하기",
          "ar": "استمر"
        },
        "Button-Subtitle": {
          "en": "Get 3 Days Free Trial",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "RightOfferConfig": {
        "QonversionID": "QON ID HERE",
        "Price": "9.99",
        "Post-Price-Text": {
          "en": "",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Box-Bold-Text": {
          "en": "Lifetime",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Box-Text": {
          "en": "one time purchase",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Button-Title": {
          "en": "CONTINUE",
          "de": "Weiter",
          "pt": "Continuar",
          "ru": "Продолжить",
          "es": "Continuar",
          "it": "Continua",
          "tr": "Devam Et",
          "fr": "Continuez",
          "zh": "繼續",
          "jp": "続行する",
          "kr": "이어하기",
          "ar": "استمر"
        },
        "Button-Subtitle": {
          "en": "Unlock Lifetime Access",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "AreYouSureQonversionID": "QON ID HERE"
    },
    {
      "id": "OTO1",
      "type": 3,
      "all-oto-iap-remove-ads": false,
      "ImagesConfig": {
        "header-title-image": "",
        "copy-image": "",
        "offer-disappears-image": "",
        "no-thanks-image": ""
      },
      "FullPriceConfig": {
        "QonversionID": "QON ID HERE",
        "Pre-Price-Text": {
          "en": "Instead of the regular price of ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Price": "14.99",
        "Post-Price-Text": {
          "en": "",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "DiscountPriceConfig": {
        "QonversionID": "QON ID HERE",
        "Pre-Price-Text": {
          "en": "Get LIFETIME ACCESS for just ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Price": "2.99",
        "Post-Price-Text": {
          "en": "",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "OrderBumpPriceConfig": {
        "QonversionID": "QON ID HERE",
        "Pre-Price-Text": {
          "en": "Also Add the 'NO-ADS' feature for only ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Price": "1.99",
        "Post-Price-Text": {
          "en": "",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "Button-Text": {
        "en": "Unlock FULL App Now!",
        "de": "",
        "pt": "",
        "ru": "",
        "es": "",
        "it": "",
        "tr": "",
        "fr": "",
        "zh": "",
        "jp": "",
        "kr": "",
        "ar": ""
      },
      "DiscountPercent": "80",
      "AreYouSureQonversionID": "Order Bump QON ID HERE"
    },
    {
      "id": "OTOL",
      "type": 3,
      "all-oto-iap-remove-ads": true,
      "ImagesConfig": {
        "header-title-image": "",
        "copy-image": "",
        "offer-disappears-image": "",
        "no-thanks-image": ""
      },
      "FullPriceConfig": {
        "QonversionID": "QON ID HERE",
        "Pre-Price-Text": {
          "en": "Instead of the regular price of ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Price": "14.99",
        "Post-Price-Text": {
          "en": "/month",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "DiscountPriceConfig": {
        "QonversionID": "QON ID HERE",
        "Pre-Price-Text": {
          "en": "Get monthly access for just ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Price": "2.99",
        "Post-Price-Text": {
          "en": " /month",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "OrderBumpPriceConfig": {
        "QonversionID": "QON ID HERE",
        "Pre-Price-Text": {
          "en": "Instead, get LIFETIME ACCESS for just ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Price": "29.99",
        "Post-Price-Text": {
          "en": "",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "Button-Text": {
        "en": "Unlock FULL App Now!",
        "de": "",
        "pt": "",
        "ru": "",
        "es": "",
        "it": "",
        "tr": "",
        "fr": "",
        "zh": "",
        "jp": "",
        "kr": "",
        "ar": ""
      },
      "DiscountPercent": "80",
      "AreYouSureQonversionID": "Order Bump QON ID HERE"
    },
    {
      "id": "OTOF",
      "type": 3,
      "all-oto-iap-remove-ads": true,
      "ImagesConfig": {
        "header-title-image": "",
        "copy-image": "",
        "offer-disappears-image": "",
        "no-thanks-image": ""
      },
      "FullPriceConfig": {
        "QonversionID": "QON ID HERE",
        "Pre-Price-Text": {
          "en": "Instead of the regular price of ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Price": "14.99",
        "Post-Price-Text": {
          "en": "/month",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "DiscountPriceConfig": {
        "QonversionID": "QON ID HERE",
        "Pre-Price-Text": {
          "en": "Get weekly access for just ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Price": "2.99",
        "Post-Price-Text": {
          "en": " /week",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "OrderBumpPriceConfig": {
        "QonversionID": "QON ID HERE",
        "Pre-Price-Text": {
          "en":
              "Instead,  start 3 days FREE Trial and then get access for only ",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        },
        "Price": "4.99",
        "Post-Price-Text": {
          "en": "/month",
          "de": "",
          "pt": "",
          "ru": "",
          "es": "",
          "it": "",
          "tr": "",
          "fr": "",
          "zh": "",
          "jp": "",
          "kr": "",
          "ar": ""
        }
      },
      "Button-Text": {
        "en": "UNLOCK pro subscription Now!",
        "de": "",
        "pt": "",
        "ru": "",
        "es": "",
        "it": "",
        "tr": "",
        "fr": "",
        "zh": "",
        "jp": "",
        "kr": "",
        "ar": ""
      },
      "DiscountPercent": "80",
      "AreYouSureQonversionID": "Order Bump QON ID HERE"
    }
  ]
};
